name: Docker Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Depoyu klonlama (Checkout the repository)
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. .NET SDK ile restore ve publish işlemleri (Restore and publish with .NET SDK)
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore "WebApplication1.csproj"

    - name: Build and publish the project
      run: dotnet publish "WebApplication1.csproj" -c Release -o /app/publish

    # 3. Docker imajını oluşturma (Build the Docker image)
    - name: Build Docker image
      run: docker build -t webapp:$(date +%s) .

    # 4. Uzak sunucuya SSH ile bağlanma ve Docker işlemleri (Deploy to the remote server)
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          # Docker container'ı durdurup kaldır (Stop and remove the running container, if it exists)
          docker stop webapp || true
          docker rm webapp || true

          # Yeni imajı çalıştırma (Run the new image)
          docker run -d --name webapp -p 5024:5024 webapp:latest
