name: Docker Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 1. Depoyu klonlama
    - name: Checkout repository
    - uses: actions/checkout@v4

    # 2. Docker imajını oluşturma
    - name: Build the Docker image
      run: docker build -t webapp:$(date +%s)
